apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivebox-deploy
  labels:
    app: hivebox-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hivebox-app
  template:
    metadata:
      labels:
        app: hivebox-app
    spec:
      containers:
        - name: hivebox-app
          image: youssefmahdy/hivebox-app:v001
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: hivebox-service
spec:
  selector:
    app: hivebox-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000