name: CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from file
        id: get_version
        run: |
          VERSION=$(grep -m1 -oP '(?<=^version=).+' setup.cfg || echo "latest")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=youssefmahdy/hivebox-app
          VERSION=${{ steps.get_version.outputs.version }}
          GIT_SHA=${{ github.sha }}
          docker build -t $IMAGE_NAME:$VERSION -t $IMAGE_NAME:$GIT_SHA -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:$GIT_SHA
          docker push $IMAGE_NAME:latest