name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python code
        run: |
          flake8 .
      
      - name: Install hadolint
        run: |
          wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.8.0/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint

      - name: Lint Dockerfile
        run: |
          hadolint dockerfile
      
      - name: Build Docker image
        run: |
          docker build --no-cache -t youssefmahdy/hivebox-app:v0.0.1 .
        
      
      
        

      # - name: Set up OpenSSF ScoreCard
      #   uses: openssf/scorecard-action@v1
      #   id: scorecard
      #   with:
      #     results_file: results.sarif
    
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m pytest -vvv
    
  quality:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@v2.0.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=hivebox
            -Dsonar.host.url=https://sonarcloud.io
      # - name: SonarQube Quality Gate Check
      #   uses: SonarSource/sonarcloud-quality-gate-action@v1.0.0
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  terrascan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Install Terrascan
        run: |
          curl -L https://github.com/tenable/terrascan/releases/latest/download/terrascan_1.19.9_Linux_x86_64.tar.gz | tar xz
          sudo mv terrascan /usr/local/bin/

      - name: Initialize Terrascan policies
        run: terrascan init

      - name: Run Terrascan on Kubernetes manifests
        run: terrascan scan -d ./KIND -i k8s --repo-url https://github.com/youssefadelG/HiveBox.git --repo-ref ${{ github.ref_name }}

      